main_tasks: 8000
randomize_start_duration: 3000
main_time: "3-00:00:00"
main_mem_per_cpu_gb: 6
main_cpus_per_task: 1
main_workers: -1
max_array_launch_parallel: true

containment_time: "1-00:00:00"
containment_tasks: 24
containment_mem_per_cpu_gb: 8
containment_cpus_per_task: 8
containment_workers: 24
fw2_duckdb_templ_path: <YOUR-ROOT-DIR>/CommonCrawl-CreativeCommons/duckdbs/fineweb-2/fw2-{language}.duckdb
fw_duckdb_templ_path: <YOUR-ROOT-DIR>/CommonCrawl-CreativeCommons/duckdbs/fineweb/fw-{dump}.duckdb
